
# Principle Component Analysis (PCA) via Eigendecomposition

Principal Component Analysis (PCA) is a linear method for dimensionality reduction. Using PCA we can project the data matrix onto a de-correlated set of bases. We take the $d$-dimensional **data covariance matrix** and diagonalize it such that the new bases are de-correlated. Then, we project the data on a subset of the news axes that has high variance (covers most of the variance of the data).

The diagonalization of the data covariance matrix in PCA can be done by performing its **eigendecomposition**. The eigendecomposition is a matrix decomposition technique for reducing a matrix into its constituent parts. More specifically, eigendecomposition decomposes a matrix into eigenvectors and eigenvalues. 

In eigendecomposition we solve the eigen equation of the data covariance matrix. The eigenvectors represent the new bases that are de-correlated. These eigenvectors are known as the priciple axes or componnents of the data. The eigenvalues represent the variance of each principle component. By using the eigenvectors corresponding to the largest $k$ eigenvalues we can project the $d$-dimensional data onto a lower $k$ dimesional space.

In this notebook, we use a toy data matrix to implement eigendecomposition based PCA using two approaches.
- Manual Implementation
- Scikit-Learn based Implementation

In [1]:
import numpy as np
from numpy.linalg import eig

from sklearn.metrics import mean_squared_error
from sklearn.decomposition import PCA

## Create a Data Matrix X from Sample Vectors

Consider that we have 3 samples each with two features:
- $\vec{x}_1 = [1, 2]$
- $\vec{x}_2 = [3, 4]$
- $\vec{x}_3 = [5, 6]$

Here, $N = 3$ and $d = 2$

Using these 3 samples we can create the data matrix X as follows:
- Use 3 samples as 3 row vectors and horizontally stack them.
        
        Dimension of X: N x d

In [2]:
# 3 Data Samples
x_1 = [1, 2]
x_2 = [3, 4]
x_3 = [5, 6]


print("\nData Matrix X:")
X = np.array([x_1, x_2, x_3])
print(X)
print("\nX Dimension (N x d): ", X.shape)


Data Matrix X:
[[1 2]
 [3 4]
 [5 6]]

X Dimension (N x d):  (3, 2)


# Manual Implementation of Eigendecomposition based PCA

There are two Steps
- Center the Data and Compute Its Covariance Matrix
- Eigendecomposition: Solve the eigen equation of the covariance matrix

### Center the Data and Compute Its Covariance Matrix 

First, we center the data by subtracting the mean of each feature (column).

Then, we compute the covariance matrix as follows. Note that in the denominator we used $N-1$, instead on $N$, for an unbiased estimator.

$ cov(X_{centered}) = \frac{X^T_{centered}.(X_{centered})}{N - 1}$

In [3]:
print("X:\n", X)
print("\nX dimension (N x d): ", X.shape)


# Compute the mean of the data (mean of each feature/column)
X_mean = np.mean(X, axis=0)
print("\nMean of X:\n", X_mean )


# Center the data (subtract the mean)
X_centered = X - X_mean
print("\nX Centered:\n", X_centered)


# Compute the covariance matrix of the data
cov_X =  X_centered.T.dot(X_centered)/(X.shape[0]-1)
print("\nCovariance Matrix:\n", cov_X)

# Compute the covariance matrix of the data using NumPy function


print("\nCovariance Matrix (using NumPy):\n", np.cov(X_centered.T))

X:
 [[1 2]
 [3 4]
 [5 6]]

X dimension (N x d):  (3, 2)

Mean of X:
 [3. 4.]

X Centered:
 [[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]

Covariance Matrix:
 [[4. 4.]
 [4. 4.]]

Covariance Matrix (using NumPy):
 [[4. 4.]
 [4. 4.]]


## Eigendecomposition

We find the eigenvectors and eigenvalues of the data covariance matrix (centered). The eigevectors are the new bases that are de-correlated. These are known as **Principle Components (PCs)**. After projecting the data matrix on the PCs, the dimension of the projected data matrix should be: $N x d$ 

Note that the dimension of X and eigenvector matrix (N = no. of data & d = no. of features) should be:

- X: N x d 

- Eigenvector: d x d


If we take a subset of the PCs ($d_{pc} \leq d$), then dimension of the projected data matrix should be: $N x d_{pc}$

Thus, to compute the projected data matrix, we need to take the dot product between "X" and "eigenvector".

Finally, after reconstructing "X", the dimension of "X_reconstructed" should be $N x d$

This can be ensured by taking the dot product between projected data matrix ($N x d_{pc}$) and the transpose of the eigenvector ($d_{pc} x d$).

Dimension of X_reconstructed: $(N x d_{pc}) x (d_{pc} x d) = N x d$

Below we show two extanples of performing eigendecomposition.

- Example 1 (No reduction in dimension): Project the Data using all PCs
- Example 2 (Dimensionality dimension): Project the Data using a subset of the PCs (e.g., the PC with the largest variance/eigenvalue)


## Example 1 (No reduction in dimension): Project the Data using all PCs

Using two PCs we project the 2D data onto 2D. Thus, there is no dimensionality reduction. As a consequence we should be able to reconstruct the original data matrix (centered). We will see that, reconstrction error would be vanishingly small.

In [4]:
# Eigendecomposition of covariance matrix: find eigenvectors & eigenvalues of cov_X
eigenvalues, eigenvectors = eig(cov_X)

print("\nEigenvectors (Principle Components):\n", eigenvectors)
print("\nEigenvalues (Variances):\n", eigenvalues)


print("\n***Observe that the first PC explains most of the variance (largest eigenvalue) in the data.***")

print("\nX dimension: ", X.shape)
print("Covariance matrix dimension: ", cov_X.shape)
print("Eigenvalues dimension: ", eigenvalues.shape)
print("Eigenvectors dimension: ", eigenvectors.shape)



# Project the data on ALL eigenvectors, i.e., Principle components (PCs)
X_projected_all_pc = X_centered.dot(eigenvectors)
print("\nProjected Data Matrix (all PC):\n", X_projected_all_pc)



# Reconstruct the original Data Matrix (centered)
X_reconstructed_all_pc = X_projected_all_pc.dot(eigenvectors.T)
print("\nX centered (reconstructed):\n", X_reconstructed_all_pc)


print("\nX Centered (original):\n", X_centered)


# Compute overall reconstruction error using the centered data
reconstruction_error_all_pc = mean_squared_error(X_centered, X_reconstructed_all_pc)
print("\nOverall Reconstruction Error (all PC): ", reconstruction_error_all_pc)


Eigenvectors (Principle Components):
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Eigenvalues (Variances):
 [8. 0.]

***Observe that the first PC explains most of the variance (largest eigenvalue) in the data.***

X dimension:  (3, 2)
Covariance matrix dimension:  (2, 2)
Eigenvalues dimension:  (2,)
Eigenvectors dimension:  (2, 2)

Projected Data Matrix (all PC):
 [[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]

X centered (reconstructed):
 [[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]

X Centered (original):
 [[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]

Overall Reconstruction Error (all PC):  1.314768175368353e-31


## Example 2 (Dimensionality dimension): Project the Data using a subset of the PCs (e.g., the PC with the largest variance/eigenvalue)

The first eigenvector (PC) has the largets eigenvalue (variance). Thus, using the first PC we project the 2D data onto 1D. This will reduce the dimension of data without losing much variance. As a result, we will see that the reconstrction error would be vanishingly small.

In [5]:

# Take the first eigenvector (PC) that has the largets eigenvalue (variance)
PC_first = eigenvectors[:,0].reshape(2, 1)
print("\nFirst Principle Component:\n", PC_first.shape)


# Project the data on the largest eigenvector, i.e., first PC
X_projected_first_pc = X_centered.dot(PC_first)
print("\nProjected Data Matrix (first PC):\n", X_projected_first_pc)



# Reconstruct the original Data Matrix (centered)
X_reconstructed_first_pc = X_projected_first_pc.dot(PC_first.T)
print("\nX centered (reconstructed):\n", X_reconstructed_first_pc)


print("\nX Centered (original):\n", X_centered)


# Compute overall reconstruction error using the centered data
reconstruction_error_first_pc = mean_squared_error(X_centered, X_reconstructed_first_pc)
print("\nOverall Reconstruction Error (first PC): ", reconstruction_error_first_pc)


print("\nIncrease in reconstruction error due to dimensionality reduction: ", (reconstruction_error_first_pc - reconstruction_error_all_pc))


First Principle Component:
 (2, 1)

Projected Data Matrix (first PC):
 [[-2.82842712]
 [ 0.        ]
 [ 2.82842712]]

X centered (reconstructed):
 [[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]

X Centered (original):
 [[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]

Overall Reconstruction Error (first PC):  1.314768175368353e-31

Increase in reconstruction error due to dimensionality reduction:  0.0


## Scikit-Learn based Implementation of PCA

We can perform PCA by using Scikit-Learn's PCA class.

We set the "n_components" parameter. It represents the number of components to keep. If n_components is not set all components are kept.

Following notebook provides a description of other parameters of the Scikit-Learn PCA:
https://github.com/rhasanbd/Dimensionality-Reduction-Get-More-From-Less-And-See-the-Unseen/blob/master/Dimensionality%20Reduction-1-Linear%20Methods.ipynb

In [6]:
# Create a PCA object
pca = PCA(n_components=2)
# Fit the object on the data matrix X
pca.fit(X)


print("\nNumber of Principle Components (Eigenvectors ): ", pca.n_components_)  

print("\nPinciple Components:\n", pca.components_)
print("\nExplained Variance (eigenvalues) by each PC: ", pca.explained_variance_)

# Percentage of variance explained for each component
print("\nExplained variance ratio: %s"
      % str(pca.explained_variance_ratio_))

print("\n***Observe that the first PC explains most of the variance in the data.***")


# Find the projected data matrix using the transform method
X_projected_sklearn = pca.transform(X)
print("\nProjected Data Matrix:\n", X_projected_sklearn)


# Reconstruct the original data matrix
X_reconstructed_sklearn = pca.inverse_transform(X_projected_sklearn)
print("\nX Reconstructed:\n", X_reconstructed_sklearn)


print("\nX (original):\n", X)


# Compute overall reconstruction error using the centered data
reconstruction_error = mean_squared_error(X, X_reconstructed_sklearn)
print("\nOverall Reconstruction Error (using centered X): ", reconstruction_error)


Number of Principle Components (Eigenvectors ):  2

Pinciple Components:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

Explained Variance (eigenvalues) by each PC:  [8.00000000e+00 2.25080839e-33]

Explained variance ratio: [1.00000000e+00 2.81351049e-34]

***Observe that the first PC explains most of the variance in the data.***

Projected Data Matrix:
 [[-2.82842712e+00  2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00 -2.22044605e-16]]

X Reconstructed:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

X (original):
 [[1 2]
 [3 4]
 [5 6]]

Overall Reconstruction Error (using centered X):  8.217301096052206e-33
